name: 'dog_transformations'
version: '1.0.0'
profile: 'dog_transformations'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  # Override with --vars '{"gcp_project": "..."}' if needed
  gcp_project: "sally-pyne-2026"

models:
  dog_transformations:
    staging:
      +materialized: view
      +schema: silver
    intermediate:
      +materialized: ephemeral
    marts:
      +materialized: table
      +schema: gold
